version: '3'
services: 
    web: 
        container_name: exampleapp
        restart: always
        build: .
        ports:
            - "5000:3000"
        # links enlaza un servidor de la app con servidor d ela base de datos, lo agrgare en database.js en ves de localhost
        links: 
            - mongo  
        volumes:
            - .:/usr/src/app
    mongo: 
        container_name: mymongodatabase
        image: mongo
        ports: 
            - "27018:27017"
        logging:
            driver: none  